#!/bin/bash
VER="2.1"

# Keybinds
KKILL="q"    # Quit out from termage
KPREV="n"    # Go to the previous image
KNEXT="o"    # Go to the next image
KREDRAW="r"  # Redraw the current image
KCENTER="c"  # Toggle centering
KINFO="i"    # Toggle info display
KNOTE="N"    # Open notes

# Colours
BLACK="\033[0m\033[30m"
RED="\033[0m\033[31m"
GREEN="\033[0m\033[32m"
YELLOW="\033[0m\033[33m"
BLUE="\033[0m\033[34m"
MAGENTA="\033[0m\033[35m"
CYAN="\033[0m\033[36m"
WHITE="\033[0m\033[37m"

# When this is set to 1 the image is centered in the frame
center="1"
# When this is set to 1 the image info is displayed
info="1"

# Function to load all passed in images
function load_images {
	# Test the params for valid files.
	IMG=0
	FILE=()
	k=0
	echo -e "${WHITE}Loading selected files..."
	for arg in "$@"; do
		if [[ `file -i "$arg" | grep image` ]]; then
			echo -e "$GREEN$arg"
			FILE[k]=$arg
			k=`expr $k + 1`
		else
			echo -e "$RED$arg"
		fi
	done
	echo -e "${WHITE}Loaded all files."
	
	if [[ ${FILE[$IMG]} == "" ]]; then
		echo -e "${RED}Error: No valid files."
		exit
	fi
}

function print_info {
	PIC="$1"
	PIF="$2"
	clear
	tput cup $(tput lines) 0
	wiw --direct "$PIC"
	tfn=`basename "$PIF"`
	echo "        Name:	$tfn"
	tdr=`readlink -f "$PIF"`
	tdr="${tdr%$tfn}"
	echo "    Location:	$tdr"
	tfs=`du -h "$PIF" | cut -d "	" -f1`
	echo "   File Size:	$tfs"
	size=`wiw --size "$PIF"`
	size1=`echo "$size" | cut -d ' ' -f1`
	size2=`echo "$size" | cut -d ' ' -f2`
	echo "  Image Size:	${size1}x${size2}"
	draw1=`echo "$PIC" | cut -d ';' -f5`
	draw2=`echo "$PIC" | cut -d ';' -f6`
	echo "  Drawn Size:	${draw1}x${draw2}"

}

# Load initial images
if [[ "$#" != "0" ]]; then
	load_images "$@"
else
	load_images *
fi

# Begin Image display loop
while true; do
	FILENAME=${FILE[$IMG]}
	# display the image
	if [[ "$center" == "1" ]]; then
		if [[ "$info" == "1" ]]; then
			CMD=`wiw --echo -m -5UN --center "$FILENAME"`
			print_info "$CMD" "$FILENAME"
		else
			wiw --clear --center -c 0-LAST "$FILENAME"
		fi
	else
		if [[ "$info" == "1" ]]; then
			CMD=`wiw --echo -m -5UN "$FILENAME"`
			print_info "$CMD" "$FILENAME"
		else
			wiw --clear "$FILENAME"
		fi
	fi
	
	# Wait for and respond to key strokes
	if [ -t 0 ]; then stty -echo -icanon time 0 min 0; fi
	KEYPRESS=''
	while true; do
		read -rsp "" -n1 KEYPRESS
		case $KEYPRESS in 
			$KKILL) # Kill termage
				clear
				exit;;
			$KPREV) # Previous image (changes to deal with dual image)
				IMG=`expr $IMG - 1`
				break;;
			$KNEXT) # Next image (changes to deal with dual image)
				IMG=`expr $IMG + 1`
				break;;
			$KREDRAW) # redraws the current image 
				break;;
			$KCENTER) # Toggle centering
				if [[ "$center" == "1" ]]; then
					center="0"
				else
					center="1"
				fi
				break;;
			$KINFO) # Toggle info
				if [[ "$info" == "1" ]]; then
					info="0"
				else
					info="1"
				fi
				break;;
			$KNOTE) # Open notes
				tfn=`basename "$FILENAME"`
				tdr=`readlink -f "$FILENAME"`
				tdr="${tdr%$tfn}"
				tnn="${tdr}.${tfn}_notes"
				if [ -f "$tnn" ]; then
					$EDITOR "$tnn"
				else
					touch "$tnn"
					$EDITOR "$tnn"
				fi	
				break;;
			*);; 
		esac
	done
	IMG=`expr $IMG % ${#FILE[@]}`
done
